### ISSUE TITLE
feature/build-logic : 그래들 관리 용이성을 위한 빌드 로직 모듈

### ISSUE THREAD

**Issue by ldh019** [GO-GO-NEVER-END/Royal-Flush-Android#3]
## 목표
- build-logic 모듈 생성

## 해야할 일
- [x] build-logic Plugin 생성
- [ ] 설명 및 사용법 문서화

**Comment by soopeach** [comment]
문서화 하는 것 좋다!!
넘 어렵네요 자료도 없구..
